--- 
- hosts: 172.31.0.26
  become: yes
  tasks:
   - name: install git 
     apt:
      name: git 
      state: present

   - name: install tree 
     apt:
      name: tree 
      stateee: present
     ignor_error: true
     

   - name: install wget 
     apt:
      name: wget 
      state: present