--- 
- hosts: 172.31.0.26
  become: yes 
  tasks: 
    - include_tasks: myfile.yml
    - name: install webserver
      apt: 
       name: apache2
       state: present

    - name: copy index file into ansible node side 
      template:
        src: index.j2
        dest: /var/www/html/index.html

    - name: i want to download remote(internet) file
      get_url:
         url: https://get.jenkins.io/war-stable/2.319.1/jenkins.war
         dest: /home/ubuntu
         force_basic_auth: yes