--- 
- hosts: mywebservers
  become: yes
  tasks: 
   - name: install java on ubuntu 
     apt:
       name: "{{javaubuntu}}"
       state: present 
     when: ansible_os_family =="Debian"

   - name: install java on redhat 
     yum:
       name: "{{javaredhat}}"
       state: present 
     when: ansible_os_family =="RedHat"





