--- 
- hosts: mywebservers
  become: yes
  tasks: 
   - name: install java on ubuntu 
     apt:
       name: {{javapackonubuntu}}
       state: present 
     when: ansible_os_family =="Debian"

   - name: install java on redhat 
      yum:
        name: {{javapackonredhat}} 
        state: present 
     when: ansible_os_family =="Redhat"




