--- 
- hosts: mywebservers 
  become: yes 
  gather_facts: yes
  tasks: 
   - name: i want to install apache2 on ubuntu 16 server
     apt:
       name: "{{mywebpackonubuntu}}"
       state: present
     when: ansible_os_family =="Debian"

   - name: i want to start apache2 service
     service:
        name: "{{mywebpackonubuntu}}"
        state: started
     when: ansible_os_family =="Debian"

   - name: i want to install webserver on ansible node
     yum:
       name: "{{mywebpackonredhat}}"
       state: present
     when: ansible_os_family =="Redhat"

   - name: i want to start httpd service
     service:
       name: "{{mywebpackonredhat}}"
       state: started
     when: ansible_os_family =="Redhat"