--- 
- hosts: all 
  become: yes 
  gather_facts: yes
  tasks: 
   - name: i want to install apache2 on ubuntu 16 server
     apt:
       name: apache2
       state: present
     when: ansible_os_family =="Debian"

   - name: i want to install webserver on redhat server
     yum:
       name: httpd
       state: present 
     when: ansible_os_family =="Redhat"
