--- 
- name: copy tomcat user file into node side 
  template: 
       src: template/tomuser.j2
       dest: /opt/tomcat/conf/tomcat-users.xml

- name: copy context file into node side
  template:
        src: template/tmcontextfile.j2
        dest: /opt/tomcat/webapps/manager/META-INF/context.xml

- name: copy host context file into node side 
  template:
        src: template/hostcontextfile.j2
        dest: /opt/tomcat/webapps/host-manager/META-INF/context.xml